version: '3'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./www:/var/www/bitrix
      - ./storage/docker/logs/nginx/:/var/log/nginx/
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - php-fpm-cli

  php-fpm-cli:
    build:
      context: ./docker
      dockerfile: php-fpm-cli.docker
    volumes:
      - ./www:/var/www/bitrix
    depends_on:
      - mysql
    tty: true

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./www:/var/www/bitrix
      - ./storage/docker/logs/php/:/var/log/php/
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker
      dockerfile: mysql.docker
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "33061:3306"