version: '3'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./app:/var/www/app
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./app:/var/www/app
      - ./storage/docker/sessions:/var/www/sessions
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker
      dockerfile: mysql.docker
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=bitrix"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=bitrix"
    ports:
      - "33061:3306"